# Generated by Django 4.2 on 2023-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpw', models.CharField(max_length=64, verbose_name='사용자비밀번호')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
            ],
            options={
                'verbose_name': '계정 관리',
                'db_table': 'accounts',
                'managed': True,
            },
        ),
    ]
