# Generated by Django 4.2 on 2023-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='userpw',
            field=models.CharField(max_length=128, verbose_name='사용자비밀번호'),
        ),
    ]
