# Generated by Django 4.2 on 2023-05-22 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=4)),
                ('kcal', models.CharField(max_length=4)),
                ('carbon', models.CharField(max_length=4)),
                ('pro', models.CharField(max_length=4)),
                ('fat', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('image_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=4)),
                ('kcal', models.CharField(max_length=4)),
                ('carbon', models.CharField(max_length=4)),
                ('pro', models.CharField(max_length=4)),
                ('fat', models.CharField(max_length=4)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('food_image', models.ImageField(upload_to=' #이미지 파일 디렉토리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
