# Generated by Django 4.2 on 2023-05-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'managed': True},
        ),
    ]
