# Generated by Django 4.2 on 2023-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gallery_carbon_alter_gallery_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
