# Generated by Django 4.2 on 2023-06-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='pro',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='total',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='carbon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='fat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='kcal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
