# Generated by Django 4.2 on 2023-05-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('food_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('food_name', models.CharField(blank=True, max_length=30, null=True)),
                ('food_calorie', models.IntegerField(blank=True, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.user')),
            ],
            options={
                'db_table': 'gallery',
                'managed': True,
            },
        ),
    ]
